export const phrases = {
  en: {
    welcome: "Welcome",
    selectAction: "Select an action",
    chooseLanguage: "Choose your language",
    changeLanguage: "⚙️ Change Language",
    menu: "📋 Menu",
    exchange: "💸 Exchange",
    history: "📓 History exchange",
    contacts: "☎️ Contacts",
    ourContacts: "Our contacts",
    site: "🌐 Our site",
    telegram: "📱 Telegram",
    phone: "📞 Phone number",
    selectTypeExchange: "Select the type of exchange:",
    exchengeType1: "Online",
    exchengeType2: "Offline",
    exchengeType3: "Transfer of funds",
  },
  ua: {
    welcome: "Ласкаво просимо",
    selectAction: "Виберіть дію",
    chooseLanguage: "Виберіть свою мову",
    changeLanguage: "⚙️ Змінити мову",
    menu: "📋 Меню",
    exchange: "💸 Обмін",
    history: "📓 Історія заявок",
    contacts: "☎️ Контакти",
    ourContacts: "Наші контакти",
    site: "🌐 Наш сайт",
    telegram: "📱 Telegram",
    phone: "📞 Номер телефону",
    selectTypeExchange: "Виберіть тип обміну:",
    exchengeType1: "Онлайн",
    exchengeType2: "Офлайн",
    exchengeType3: "Переказ коштів",
  },
  ru: {
    welcome: "Добро пожаловать",
    selectAction: "Выберите действие",
    chooseLanguage: "Выберите ваш язык",
    changeLanguage: "⚙️ Изменить язык",
    menu: "📋 Меню",
    exchange: "💸 Обмен",
    history: "📓 История заявок",
    contacts: "☎️ Контакты",
    ourContacts: "Наши контакты",
    site: "🌐 Наш сайт",
    telegram: "📱 Telegram",
    phone: "📞 Номер телефона",
    selectTypeExchange: "Выберите тип обмена:",
    exchengeType1: "Онлайн",
    exchengeType2: "Офлайн",
    exchengeType3: "Перевод средств",
  },
};
