export const phrases = {
  en: {
    welcome: "Welcome",
    selectAction: "Select an action",
    chooseLanguage: "Choose your language",
    changeLanguage: "⚙️ Change Language",
    menu: "📋 Menu",
    exchange: "💸 Exchange",
    history: "📓 History exchange",
    contacts: "☎️ Contacts",
    ourContacts: "Our contacts",
    site: "🌐 Our site",
    telegram: "📱 Telegram",
    phone: "📞 Phone number",
    selectTypeExchange: "Select the type of exchange:",
    exchengeType1: "Online",
    exchengeType2: "Offline",
    exchengeType3: "Transfer of funds",
    selectTypeTransfer: "Select the type of transfer:",
    back: "⬅️ Back",
    forward: "➡️ Forward",
    country: "Country:",
    selectCity: "Select city:",
    selectCountry: "Select country:",
    chooseGiveCurrencyType: "Choose the type of currency you want to give:",
    chooseGiveCurrency: "Choose the currency you want to give:",
    chooseGetCurrency: "Choose the currency you want to receive:",
    youWantExchange: "You want to exchange",
    for: "for",
    exchangeRate: "Exchange:",
    wantGive: "I want to give X amount of",
    wantGet: "I want to receive X amount of",
    currency: "",
    enterGiveAmount: `Enter the amount you want to give`,
    enterGetAmount: `Enter the amount you want to receive`,
    city: "City",
    name: "Name",
    from: "From",
    to: "To",
    give: "Give",
    receive: "Receive",
    approximateExchangeRate: "Approximate exchange rate",
    submit: "Submit request",
    correctAmountError: "Please enter the correct amount. Example: 100",
    successfullySent: "Your application has been successfully sent!",
    exchangeList: "List of applications for exchange:",
    inProcess: "In process",
    canceled: "Canceled",
    completed: "Completed",
    enterCardNumber: "Enter your card number:",
    enterCryptoWallet: "Enter your crypto wallet:",
    wallet: "Wallet",
    forBusiness: "💼 For business",
    deposit: "💵 Deposit",
    goldDeposit: "Deposit in gold",
    dollarDeposit: "Deposit in dollars",
    moreInfo: "More info",
  },
  ua: {
    welcome: "Ласкаво просимо",
    selectAction: "Виберіть дію",
    chooseLanguage: "Виберіть свою мову",
    changeLanguage: "⚙️ Змінити мову",
    menu: "📋 Меню",
    exchange: "💸 Обмін",
    history: "📓 Історія заявок",
    contacts: "☎️ Контакти",
    ourContacts: "Наші контакти",
    site: "🌐 Наш сайт",
    telegram: "📱 Telegram",
    phone: "📞 Номер телефону",
    selectTypeExchange: "Виберіть тип обміну:",
    exchengeType1: "Онлайн",
    exchengeType2: "Офлайн",
    exchengeType3: "Переказ коштів",
    selectTypeTransfer: "Виберіть тип переводу:",
    back: "⬅️ Назад",
    forward: "➡️ Вперед",
    country: "Країна:",
    selectCity: "Виберіть місто:",
    selectCountry: "Виберіть країну:",
    chooseGiveCurrencyType: "Виберіть тип валюти яку ви хочете віддати:",
    chooseGiveCurrency: "Виберіть валюту яку хочете віддати:",
    chooseGetCurrency: "Виберіть валюту яку хочете отримати:",
    youWantExchange: "Ви хочете обміняти",
    for: "на",
    exchangeRate: "Курс:",
    wantGive: "Хочу віддати X кількість",
    wantGet: "Хочу отримати X кількість",
    enterGiveAmount: `Введіть суму яку хочете віддати`,
    enterGetAmount: `Введіть суму яку хочете отримати`,
    city: "Місто",
    name: "Ім'я",
    from: "Звідки",
    to: "Куди",
    give: "Віддаю",
    receive: "Отримую",
    approximateExchangeRate: "Приблизний курс",
    submit: "Відправити заявку",
    correctAmountError: "Будь ласка, введіть коректну суму. Приклад: 100",
    successfullySent: "Ваша заявка успішно надіслана!",
    exchangeList: "Список заявок на обмін:",
    inProcess: "В обробці",
    canceled: "Відмінена",
    completed: "Завершена",
    enterCardNumber: "Введіть номер вашої картки:",
    enterCryptoWallet: "Введіть свій крипто гаманець:",
    wallet: "Гаманець",
    forBusiness: "💼 Для бізнесу",
    deposit: "💵 Депозит",
    goldDeposit: "Депозит в золоті",
    dollarDeposit: "Депозит в долларах",
    moreInfo: "Більше інформації",
  },
  ru: {
    welcome: "Добро пожаловать",
    selectAction: "Выберите действие",
    chooseLanguage: "Выберите ваш язык",
    changeLanguage: "⚙️ Изменить язык",
    menu: "📋 Меню",
    exchange: "💸 Обмен",
    history: "📓 История заявок",
    contacts: "☎️ Контакты",
    ourContacts: "Наши контакты",
    site: "🌐 Наш сайт",
    telegram: "📱 Telegram",
    phone: "📞 Номер телефона",
    selectTypeExchange: "Выберите тип обмена:",
    exchengeType1: "Онлайн",
    exchengeType2: "Офлайн",
    exchengeType3: "Перевод средств",
    selectTypeTransfer: "Выберите тип перевода:",
    back: "⬅️ Назад",
    forward: "➡️ Вперед",
    country: "Страна:",
    selectCity: "Выберите город:",
    selectCountry: "Выберите страну:",
    chooseGiveCurrencyType: "Выберите тип валюты, которую вы хотите отдать:",
    chooseGiveCurrency: "Выберите валюту, которую хотите отдать:",
    chooseGetCurrency: "Выберите валюту, которую хотите получить:",
    youWantExchange: "Вы хотите обменять",
    for: "на",
    exchangeRate: "Курс:",
    wantGive: "Хочу отдать X количество",
    wantGet: "Хочу получить X количество",
    enterGiveAmount: `Введите сумму, которую хотите отдать`,
    enterGetAmount: `Введите сумму, которую хотите получить`,
    city: "Город",
    name: "Имя",
    from: "Откуда",
    to: "Куда",
    give: "Отдаю",
    receive: "Получаю",
    approximateExchangeRate: "Приблезительный курс",
    submit: "Отправить заявку",
    correctAmountError: "Введите корректную сумму. Пример: 100",
    successfullySent: "Ваша заявка успешно отправлена!",
    exchangeList: "Список заявок на обмен:",
    inProcess: "В обработке",
    canceled: "Отменена",
    completed: "Завершена",
    enterCardNumber: "Введите номер вашей карты:",
    enterCryptoWallet: "Введите свой криптокошелек:",
    wallet: "Кошелек",
    forBusiness: "💼 Для бизнеса",
    deposit: "💵 Депозит",
    goldDeposit: "Депозит в золоте",
    dollarDeposit: "Депозит в долларах",
    moreInfo: "Больше информации",
  },
};
